### ISSUE TITLE
Create a separate kitchen screen/tab for dishes addition updates

### ISSUE THREAD

**Issue by hrsraj** [ThatNinjaGuy/Waiter#27]
Create a separate kitchen screen/tab for dishes addition updates:
Each dish order taken will be updated here along with table number as key or tagged along
One the order is completed, there should be a status update of that dish. (PS- As soon as dish status is shifted to ready, waiter should be notified)

**Comment by ThatNinjaGuy** [comment]
@hrsraj The orders screen indicates the same. Notification feature for waiters and maybe kitchen is required. This is a separate issue created for that.

**Comment by ThatNinjaGuy** [comment]
Do you think it is still required? Please provide more information if the orders screen doesn't meet the needs

**Comment by ThatNinjaGuy** [comment]
Complete
